### PR TITLE
re-generated files from qm

### PR DESCRIPTION
**Pull request by dev-pmallapp**

### CODE REVIEW

**Review by dev-pmallapp — COMMENTED** [review]
done

**Comment by vChavezB** [comment]
Thanks for your PR. Could you specify the changes you made ? From the branch name and the commit it seems this PR addresses updating the Port for v7.3.0 ?

In addition please mention for which version of the Arduino Core ESP32 this works.

Last version I ported was for ESP32 Core v2.0.11. Now the latest version is 3.0.5.

**Comment by vChavezB** [comment]
Unfortunately I have tested your code via github action and it does not compile. Neither for esp32 core version 2.0.17 nor for version 3.0.5.  I made a test branch to check your changes as I cannot fork your fork.

https://github.com/vChavezB/qpcpp_esp32/blob/test_7.3.0/

From what I can see you have a separate folder for include headers. This does not work out of the box for arduino. All your code has to be in the src folder. This is ugly, but it is the way Arduino works.  See https://github.com/arduino/arduino-cli/issues/501

The specific errors I got for the build are located in the github action runner:

https://github.com/vChavezB/qpcpp_esp32/actions/runs/11194440949/job/31120920028

My solution was to put all the headers and source files in a flat structure in src.

Please add my github actions workflow in your branch so you can automatically test if your PR can be compiled.

https://github.com/vChavezB/qpcpp_esp32/blob/test_7.3.0/.github/workflows/build.yml

**Comment by dev-pmallapp** [comment]
Hi ,
sorry about the PR, I forked and try to merge for experimentation, but it
created PR by accident, this is untested code, please delete the PR at will

**Comment by vChavezB** [comment]
Yes, I think this happens by default. If you merge from your fork it will suggest that the merge be done to the default branch of the original repo.

No problem, PR closed !

**Pull request closed without merging**
